### PR TITLE
[Resolves #43] fixed test suite issues in master, added association between lifehack and review

### LINKED ISSUE #43: make tests pass in master, fix merge conflicts that emerged from merging issue #3

### PR DESCRIPTION
**Pull request by veneziacarl**
#43

### CODE REVIEW

File: spec/factories/factory.rb [hunk 1]
```diff
@@ -7,4 +7,9 @@
     sequence(:email) { |n| "user#{n}@launch.com" }
     password "SuperPWthatislong"
   end
+
+  factory :lifehack do
```
Comment (mlg-) [inline spec/factories/factory.rb:11]: I forget if I told you or someone else this before, but eventually you might want to break all your factories out into one per file for ease of use.
